#!/usr/bin/env bash
# LFS-AI - Build and install Glibc
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=glibc
VERSION=2.43
TZVERSION=2026a

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase1"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
[ -f "/sources/glibc-fhs-1.patch" ] || die "Missing patch: /sources/glibc-fhs-1.patch"
[ -f "/sources/tzdata$TZVERSION.tar.gz" ] || die "Missing source archive: /sources/tzdata$TZVERSION.tar.gz"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
sed -e '/while..ancount/c\  for (; ancount > 0; --ancount)'  \
    -e '/binary_hnok..expected/s/expected_name/name_buffer/' \
    -i resolv/nss_dns/dns-host.c

run_log patch -Np1 -i ../glibc-fhs-1.patch
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

mkdir -p build
cd       build

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
printf 'rootsbindir=/usr/sbin\n' > configparms

run_log ../configure --prefix=/usr                   \
                     --disable-werror                \
                     --disable-nscd                  \
                     libc_cv_slibdir="/usr/lib"      \
                     --enable-stack-protector=strong \
                     --enable-kernel=6.6
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
touch /etc/ld.so.conf
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

sed '/RTLDLIST=/s@/usr@@g' -i "/usr/pkg/$PACKAGE/$VERSION/usr/bin/ldd"

run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" localedata/install-locales
run_log sh -c "sed '1,3d; s#/# #; s/[[:space:]]\\\\$//' '/sources/$PACKAGE-$VERSION/localedata/SUPPORTED' > '/usr/pkg/$PACKAGE/$VERSION/usr/share/i18n/SUPPORTED'"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files systemd
group: files systemd
shadow: files systemd

hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

printf '%sPackaging tzdata%s...%s\n' "$MAGENTA" "$TZVERSION" "$RESET"
run_log tar -xf "../../tzdata$TZVERSION.tar.gz"

ZONEINFO="/usr/pkg/$PACKAGE/$VERSION/usr/share/zoneinfo"
run_log mkdir -pv "$ZONEINFO"/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward; do
    run_log zic -L /dev/null   -d "$ZONEINFO"       "${tz}"
    run_log zic -L /dev/null   -d "$ZONEINFO/posix" "${tz}"
    run_log zic -L leapseconds -d "$ZONEINFO/right" "${tz}"
done

run_log cp -v zone.tab zone1970.tab iso3166.tab "$ZONEINFO"
run_log zic -d "$ZONEINFO" -p America/Toronto
unset ZONEINFO tz

run_log ln -svf "/usr/pkg/$PACKAGE/$VERSION/usr/share/zoneinfo/America/Toronto" "/usr/pkg/$PACKAGE/$VERSION/etc/localtime"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib

EOF

cat >> /etc/ld.so.conf << "EOF"
# Add an include directory
include /etc/ld.so.conf.d/*.conf

EOF
run_log mkdir -pv /etc/ld.so.conf.d

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

cd /sources
rm -rf "$PACKAGE-$VERSION"

