#!/usr/bin/env bash
# LFS-AI - Build and install Bzip
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=bzip2
VERSION=1.0.8

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

[ -f "/sources/$PACKAGE-$VERSION-install_docs-1.patch" ] || {
    printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION-install_docs-1.patch" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np1 -i "../$PACKAGE-$VERSION-install_docs-1.patch"
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make -f Makefile-libbz2_so

run_log make clean

run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make PREFIX=/usr/pkg/$PACKAGE/$VERSION/usr install

run_log cp -a  libbz2.so.* "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log ln -sf "libbz2.so.$VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libbz2.so"

run_log ln -sf "libbz2.so.$VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libbz2.so.1"

run_log cp     bzip2-shared "/usr/pkg/$PACKAGE/$VERSION/usr/bin/bzip2"
for i in /usr/pkg/"$PACKAGE"/"$VERSION"/usr/bin/{bzcat,bunzip2}; do
  run_log ln -sf bzip2 "$i"
done
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
