#!/usr/bin/env bash
# LFS-AI - Build and install Bzip2
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=bzip2
VERSION=1.0.8

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
[ -f "/sources/$PACKAGE-$VERSION-install_docs-1.patch" ] || die "Missing patch: /sources/$PACKAGE-$VERSION-install_docs-1.patch"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i "../$PACKAGE-$VERSION-install_docs-1.patch"
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make -f Makefile-libbz2_so

run_log make clean

run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make PREFIX=/usr/pkg/$PACKAGE/$VERSION/usr install

run_log cp -va  libbz2.so.* "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log ln -svf "libbz2.so.$VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libbz2.so"

run_log ln -svf "libbz2.so.$VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libbz2.so.1"

run_log cp -v bzip2-shared "/usr/pkg/$PACKAGE/$VERSION/usr/bin/bzip2"
for i in /usr/pkg/"$PACKAGE"/"$VERSION"/usr/bin/{bzcat,bunzip2}; do
    run_log ln -svf bzip2 "$i"
done
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
