#!/usr/bin/env bash
# LFS-AI - Build and install Readline
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=readline
VERSION=8.3
PATCH=readline83

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

for p in {001..003}; do
    [ -f "/sources/$PATCH-$p" ] || {
        printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
            "/sources/$PATCH-$p" >&2
        exit 1
    }
done

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np0 -i "../$PATCH-001"
run_log patch -Np0 -i "../$PATCH-002"
run_log patch -Np0 -i "../$PATCH-003"

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr    \
                    --disable-static \
                    --with-curses    \
                    --docdir="/usr/share/doc/$PACKAGE-$VERSION"
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make SHLIB_LIBS="-lncursesw"
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

mkdir -p "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
cp -v doc/*.{ps,pdf,html,dvi} "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf "${GREEN}Package successful!${RESET}\n"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
