#!/usr/bin/env bash
# LFS-AI - Build and install Tcl
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=tcl
VERSION=8.6.17
MAJOR_VERSION=8.6
PACKAGENAME=tcl8.6.17

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGENAME-src.tar.gz" ] || die "Missing source archive: /sources/$PACKAGENAME-src.tar.gz"
[ -f "/sources/$PACKAGENAME-html.tar.gz" ] || die "Missing source archive: /sources/$PACKAGENAME-html.tar.gz"

cd /sources

rm -rf "$PACKAGENAME"
tar -xf "$PACKAGENAME-src.tar.gz"
cd "/sources/$PACKAGENAME"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
SRCDIR="$(pwd)"
cd unix
run_log ./configure --prefix=/usr           \
                    --mandir=/usr/share/man \
                    --enable-64bit          \
                    --disable-rpath
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make

sed -e "s|$SRCDIR/unix|/usr/lib|" \
    -e "s|$SRCDIR|/usr/include|"  \
    -i tclConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.12|/usr/lib/tdbc1.1.12|" \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12/generic|/usr/include|"     \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12/library|/usr/lib/tcl$MAJOR_VERSION|"  \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12|/usr/include|"             \
    -i pkgs/tdbc1.1.12/tdbcConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/itcl4.3.4|/usr/lib/itcl4.3.4|" \
    -e "s|$SRCDIR/pkgs/itcl4.3.4/generic|/usr/include|"    \
    -e "s|$SRCDIR/pkgs/itcl4.3.4|/usr/include|"            \
    -i pkgs/itcl4.3.4/itclConfig.sh

unset SRCDIR
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log chmod -v 644 "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libtclstub$MAJOR_VERSION.a"
run_log chmod -v u+w "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libtcl$MAJOR_VERSION.so"

run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install-private-headers

run_log ln -svf "tclsh$MAJOR_VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/bin/tclsh"
run_log mv -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man3/"{Thread,Tcl_Thread}.3

cd ..
tar -xf "../$PACKAGENAME-html.tar.gz" --strip-components=1
run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
run_log cp -v -r  ./html/* "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGENAME"
