#!/usr/bin/env bash
# LFS-AI - Build and install Tcl
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=tcl
VERSION=8.6.17
MAJOR_VERSION=8.6
PACKAGENAME=tcl8.6.17

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGENAME-src.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGENAME-src.tar.gz" >&2
    exit 1
}

[ -f "/sources/$PACKAGENAME-html.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGENAME-html.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGENAME"
tar -xf "$PACKAGENAME-src.tar.gz"
cd "/sources/$PACKAGENAME"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
SRCDIR="$(pwd)"
cd unix
run_log ./configure --prefix=/usr           \
                    --mandir=/usr/share/man \
                    --enable-64bit          \
                    --disable-rpath
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make

sed -e "s|$SRCDIR/unix|/usr/lib|" \
    -e "s|$SRCDIR|/usr/include|"  \
    -i tclConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.12|/usr/lib/tdbc1.1.12|" \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12/generic|/usr/include|"     \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12/library|/usr/lib/tcl$MAJOR_VERSION|"  \
    -e "s|$SRCDIR/pkgs/tdbc1.1.12|/usr/include|"             \
    -i pkgs/tdbc1.1.12/tdbcConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/itcl4.3.4|/usr/lib/itcl4.3.4|" \
    -e "s|$SRCDIR/pkgs/itcl4.3.4/generic|/usr/include|"    \
    -e "s|$SRCDIR/pkgs/itcl4.3.4|/usr/include|"            \
    -i pkgs/itcl4.3.4/itclConfig.sh

unset SRCDIR
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

chmod --quiet 644 "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libtclstub$MAJOR_VERSION.a"
chmod --quiet u+w "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libtcl$MAJOR_VERSION.so"

run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install-private-headers

run_log ln -svf "tclsh$MAJOR_VERSION" "/usr/pkg/$PACKAGE/$VERSION/usr/bin/tclsh"
run_log mv -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man3/"{Thread,Tcl_Thread}.3

cd ..
tar -xf "../$PACKAGENAME-html.tar.gz" --strip-components=1
mkdir -p "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
run_log cp -v -r  ./html/* "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGENAME"
