#!/usr/bin/env bash
# LFS-AI - Build and install Expect
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=expect
VERSION=5.45.4
PACKAGENAME=expect5.45.4

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGENAME.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGENAME.tar.gz" >&2
    exit 1
}

[ -f "/sources/$PACKAGE-$VERSION-gcc15-1.patch" ] || {
    printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION-gcc15-1.patch" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGENAME"
tar -xf "$PACKAGENAME.tar.gz"
cd "/sources/$PACKAGENAME"

run_log python3 -c 'from pty import spawn; spawn(["echo", "ok"])'

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np1 -i "../$PACKAGE-$VERSION-gcc15-1.patch"
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr           \
                    --with-tcl=/usr/lib     \
                    --enable-shared         \
                    --enable-64bit          \
                    --disable-rpath         \
                    --mandir=/usr/share/man \
                    --with-tclinclude=/usr/include
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log ln -svf "$PACKAGENAME/lib$PACKAGENAME.so" "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGENAME"
