#!/usr/bin/env bash
# LFS-AI - Build and install Expect
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=expect
VERSION=5.45.4
PACKAGENAME=expect5.45.4

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGENAME.tar.gz" ] || die "Missing source archive: /sources/$PACKAGENAME.tar.gz"
[ -f "/sources/$PACKAGE-$VERSION-gcc15-1.patch" ] || die "Missing patch: /sources/$PACKAGE-$VERSION-gcc15-1.patch"

cd /sources

rm -rf "$PACKAGENAME"
tar -xf "$PACKAGENAME.tar.gz"
cd "/sources/$PACKAGENAME"

run_log python3 -c 'from pty import spawn; spawn(["echo", "ok"])'

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i "../$PACKAGE-$VERSION-gcc15-1.patch"
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr           \
                    --with-tcl=/usr/lib     \
                    --enable-shared         \
                    --enable-64bit          \
                    --disable-rpath         \
                    --mandir=/usr/share/man \
                    --with-tclinclude=/usr/include
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log ln -svf "$PACKAGENAME/lib$PACKAGENAME.so" "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGENAME"
