#!/usr/bin/env bash
# LFS-AI - Build and install Binutils
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=binutils
VERSION=2.46.0

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

mkdir -p build
cd       build

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ../configure --prefix=/usr       \
                     --sysconfdir=/etc   \
                     --enable-gold=yes   \
                     --enable-ld=default \
                     --enable-libgm2     \
                     --enable-plugins    \
                     --enable-shared     \
                     --disable-werror    \
                     --enable-64-bit-bfd \
                     --enable-new-dtags  \
                     --with-system-zlib  \
                     --enable-lto        \
                     --enable-default-hash-style=gnu
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make tooldir=/usr
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" tooldir=/usr install
printf "${GREEN}Package successful!${RESET}\n"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
