#!/usr/bin/env bash
# LFS-AI - Build and install Gcc
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=gcc
VERSION=15.2.0

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase2/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
sed -i 's/char [*]q/const &/' libgomp/affinity-fmt.c

case "$(uname -m)" in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac


mkdir -p build
cd       build

run_log env LD=ld ../configure             \
                  --prefix=/usr            \
                  --enable-languages=c,c++,cobol,fortran,go,objc,obj-c++,m2,lto \
                  --enable-default-pie     \
                  --enable-default-ssp     \
                  --enable-host-pie        \
                  --disable-multilib       \
                  --disable-bootstrap      \
                  --disable-fixincludes    \
                  --enable-plugins         \
                  --enable-lto             \
                  --with-zstd              \
                  --with-system-zlib
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
ulimit -s -H unlimited

run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

chown --quiet -R root:root \
    "/usr/pkg/$PACKAGE/$VERSION/usr/lib/gcc/$(gcc -dumpmachine)/$VERSION/include"{,-fixed}

run_log ln -svfr "/usr/pkg/$PACKAGE/$VERSION/usr/bin/cpp" "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log ln -svf gcc.1 "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man1/cc.1"

mkdir -p "/usr/pkg/$PACKAGE/$VERSION/usr/lib/bfd-plugins"
run_log ln -svf "../../libexec/gcc/$(gcc -dumpmachine)/$VERSION/liblto_plugin.so" \
        "/usr/pkg/$PACKAGE/$VERSION/usr/lib/bfd-plugins/"

mkdir -p "/usr/pkg/$PACKAGE/$VERSION/usr/share/gdb/auto-load/usr/lib"
for f in "/usr/pkg/$PACKAGE/$VERSION/usr/lib/"*gdb.py; do
    [ -e "$f" ] || continue
    run_log mv -v "$f" "/usr/pkg/$PACKAGE/$VERSION/usr/share/gdb/auto-load/usr/lib"
done
printf "${GREEN}Package successful!${RESET}\n"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
