#!/usr/bin/env bash
# LFS-AI - Build and install Perl
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=perl
VERSION=5.42.1
MAJOR_VERSION=5.42

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase3/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

export BUILD_ZLIB=False
export BUILD_BZIP2=0

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log sh Configure -des                                                      \
                     -D prefix="/usr"                                          \
                     -D vendorprefix="/usr"                                    \
                     -D privlib="/usr/lib/perl5/$MAJOR_VERSION/core_perl"      \
                     -D archlib="/usr/lib/perl5/$MAJOR_VERSION/core_perl"      \
                     -D sitelib="/usr/lib/perl5/$MAJOR_VERSION/site_perl"      \
                     -D sitearch="/usr/lib/perl5/$MAJOR_VERSION/site_perl"     \
                     -D vendorlib="/usr/lib/perl5/$MAJOR_VERSION/vendor_perl"  \
                     -D vendorarch="/usr/lib/perl5/$MAJOR_VERSION/vendor_perl" \
                     -D man1dir="/usr/share/man/man1"                          \
                     -D man3dir="/usr/share/man/man3"                          \
                     -D pager="/usr/bin/less -isR"                             \
                     -D useshrplib                                             \
                     -D optimize="$ADD_CFLAGS"                                 \
                     -D usethreads
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install
printf "${GREEN}Package successful!${RESET}\n"

unset BUILD_ZLIB BUILD_BZIP2

cd /sources
rm -rf "$PACKAGE-$VERSION"
