#!/usr/bin/env bash
# LFS-AI - Build and install Libelf
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=elfutils
VERSION=0.194

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase4"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.bz2" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.bz2"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.bz2"
cd "/sources/$PACKAGE-$VERSION"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr        \
                    --disable-debuginfod \
                    --enable-libdebuginfod=dummy
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make -C lib
run_log make -C libelf
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" -C libelf install

run_log install -v -dm755 "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
run_log install -vm644 config/libelf.pc "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
run_log rm "/usr/pkg/$PACKAGE/$VERSION/usr/lib/libelf.a"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"

