#!/usr/bin/env bash
# LFS-AI - Build and install Sqlite
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=sqlite
VERSION=3.51.3
DOC_NAME=sqlite-doc
SRC_NAME=sqlite-autoconf
SRC_VERSION=3510300

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$SRC_NAME-$SRC_VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$SRC_NAME-$SRC_VERSION.tar.gz" >&2
    exit 1
}

[ -f "/sources/$DOC_NAME-$SRC_VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$DOC_NAME-$SRC_VERSION.tar.xz" >&2
    exit 1
}

cd /sources

rm -rf "$SRC_NAME-$SRC_VERSION"
tar -xf "$SRC_NAME-$SRC_VERSION.tar.gz"
cd "/sources/$SRC_NAME-$SRC_VERSION"

tar -xf ../$DOC_NAME-$SRC_VERSION.tar.xz

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr                                \
                    --enable-fts{4,5}                            \
                    CPPFLAGS="-D SQLITE_ENABLE_COLUMN_METADATA=1 \
                              -D SQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                              -D SQLITE_ENABLE_DBSTAT_VTAB=1     \
                              -D SQLITE_SECURE_DELETE=1"
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make LDFLAGS.rpath=""
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log install -v -m755 -d "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
run_log cp -v -R "$DOC_NAME-$SRC_VERSION"/* "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$SRC_NAME-$SRC_VERSION"
