#!/usr/bin/env bash
# LFS-AI - Build and install Sqlite
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=sqlite
VERSION=3.51.3
DOC_NAME=sqlite-doc
SRC_NAME=sqlite-autoconf
SRC_VERSION=3510300

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$SRC_NAME-$SRC_VERSION.tar.gz" ] || die "Missing source archive: /sources/$SRC_NAME-$SRC_VERSION.tar.gz"
[ -f "/sources/$DOC_NAME-$SRC_VERSION.tar.xz" ] || die "Missing source archive: /sources/$DOC_NAME-$SRC_VERSION.tar.xz"

cd /sources

rm -rf "$SRC_NAME-$SRC_VERSION"
tar -xf "$SRC_NAME-$SRC_VERSION.tar.gz"
cd "/sources/$SRC_NAME-$SRC_VERSION"

tar -xf ../$DOC_NAME-$SRC_VERSION.tar.xz

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr                                \
                    --enable-fts{4,5}                            \
                    CPPFLAGS="-D SQLITE_ENABLE_COLUMN_METADATA=1 \
                              -D SQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                              -D SQLITE_ENABLE_DBSTAT_VTAB=1     \
                              -D SQLITE_SECURE_DELETE=1"
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make LDFLAGS.rpath=""
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log install -v -m755 -d "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
run_log cp -v -R "$DOC_NAME-$SRC_VERSION"/* "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$SRC_NAME-$SRC_VERSION"
