#!/usr/bin/env bash
# LFS-AI - Build and install Python
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=python
VERSION=3.14.3
MAJOR_VERSION=3.14
SRC_PACKAGE=Python

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$SRC_PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$SRC_PACKAGE-$VERSION.tar.xz"
[ -f "/sources/Python-3.14.3-security_fixes-1.patch" ] || die "Missing patch: /sources/Python-3.14.3-security_fixes-1.patch"
[ -f "/sources/$PACKAGE-$VERSION-docs-html.tar.bz2" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION-docs-html.tar.bz2"

cd /sources

rm -rf "$SRC_PACKAGE-$VERSION"
tar -xf "$SRC_PACKAGE-$VERSION.tar.xz"
cd "/sources/$SRC_PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i ../Python-3.14.3-security_fixes-1.patch
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr          \
                    --enable-shared        \
                    --with-system-expat    \
                    --enable-optimizations
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log install -v -dm755 "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION/html"

run_log tar --strip-components=1  \
            --no-same-owner       \
            --no-same-permissions \
            -C "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION/html" \
            -xvf "../$PACKAGE-$VERSION-docs-html.tar.bz2"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/lib/python$MAJOR_VERSION/site-packages/custom.pth" << EOF
/usr/lib/python$MAJOR_VERSION/site-packages
EOF

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cat > /etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

cd /sources
rm -rf "$SRC_PACKAGE-$VERSION"
