#!/usr/bin/env bash
# LFS-AI - Build and install Ninja
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=ninja
VERSION=1.13.2

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log python3 configure.py --bootstrap --verbose
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log install -v -dm755 "/usr/pkg/$PACKAGE/$VERSION/usr/bin/"
run_log install -vm755 ninja "/usr/pkg/$PACKAGE/$VERSION/usr/bin/"
run_log install -vDm644 misc/bash-completion "/usr/pkg/$PACKAGE/$VERSION/usr/share/bash-completion/completions/ninja"
run_log install -vDm644 misc/zsh-completion  "/usr/pkg/$PACKAGE/$VERSION/usr/share/zsh/site-functions/_ninja"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
