#!/usr/bin/env bash
# LFS-AI - Build and install Coreutils
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=coreutils
VERSION=9.10

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase4"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
[ -f "/sources/$PACKAGE-$VERSION-i18n-1.patch" ] || die "Missing patch: /sources/$PACKAGE-$VERSION-i18n-1.patch"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i ../$PACKAGE-$VERSION-i18n-1.patch
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log autoreconf -fv
run_log automake -af
FORCE_UNSAFE_CONFIGURE=1 run_log ./configure \
                                 --prefix=/usr
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/sbin"
run_log mv -v "/usr/pkg/$PACKAGE/$VERSION/usr/bin/chroot" "/usr/pkg/$PACKAGE/$VERSION/usr/sbin"

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man8"
run_log mv -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man1/chroot.1" "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man8/chroot.8"
sed -i 's/"1"/"8"/' "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man8/chroot.8"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
