#!/usr/bin/env bash
# LFS-AI - Build and install Rsync
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=rsync
VERSION=3.4.1

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
[ -f "/sources/$PACKAGE-$VERSION-security_fix-1.patch" ] || die "Missing patch: /sources/$PACKAGE-$VERSION-security_fix-1.patch"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sCreating %s user...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"

if ! getent group rsyncd >/dev/null 2>&1; then
    printf 'Group rsyncd does not exist. Creating it now.\n'
    run_log groupadd -g 48 rsyncd
    printf 'Group rsyncd created successfully.\n'
else
    printf 'Group rsyncd already exists.\n'
fi

if ! id rsyncd >/dev/null 2>&1; then
    printf 'User rsyncd does not exist. Creating account...\n'
    run_log useradd -c "rsyncd Daemon" -g rsyncd -s /bin/false -u 48 rsyncd
    printf 'User rsyncd created successfully.\n'
else
    printf 'User rsyncd already exists. No action taken.\n'
fi
printf '%sUser creation successful!%s\n' "$GREEN" "$RESET"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i ../$PACKAGE-$VERSION-security_fix-1.patch
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr    \
                    --disable-xxhash \
                    --without-included-zlib
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
