#!/usr/bin/env bash
# LFS-AI - Build and install Rsync
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=rsync
VERSION=3.4.1

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

[ -f "/sources/$PACKAGE-$VERSION-security_fix-1.patch" ] || {
    printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION-security_fix-1.patch" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "\n${MAGENTA}Creating %s user...${RESET}\n" "$PACKAGE"

if ! getent group rsyncd >/dev/null 2>&1; then
    printf "Group rsyncd does not exist. Creating it now.\n"
    run_log groupadd -g 48 rsyncd
    printf "Group rsyncd created successfully.\n"
else
    printf "Group rsyncd already exists.\n"
fi

if ! id rsyncd >/dev/null 2>&1; then
    printf "User rsyncd does not exist. Creating account...\n"
    run_log useradd -c "rsyncd Daemon" -g rsyncd -s /bin/false -u 48 rsyncd
    printf "User rsyncd created successfully.\n"
else
    printf "User rsyncd already exists. No action taken.\n"
fi
printf "${GREEN}User creation successful!${RESET}\n"

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np1 -i ../$PACKAGE-$VERSION-security_fix-1.patch
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr    \
                    --disable-xxhash \
                    --without-included-zlib
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
