#!/usr/bin/env bash
# LFS-AI - Build and install Limine
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=limine
VERSION=11.2.0

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase4"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/v$VERSION-binary.tar.gz" ] || die "Missing source archive: /sources/v$VERSION-binary.tar.gz"

cd /sources

rm -rf "limine"
tar -xf "v$VERSION-binary.tar.gz"
cd "/sources/limine"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make

rm -f limine.exe

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine"
run_log cp -v BOOT* "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/"
run_log cp -v limine-* "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"

run_log mkdir -pv /boot/EFI/BOOT
run_log cp -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/BOOTX64.EFI" /boot/EFI/BOOT/BOOTX64.EFI

run_log mkdir -pv /boot/EFI/LFS
run_log cp -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/BOOTX64.EFI" /boot/EFI/LFS/LIMINEX64.EFI

cat > /boot/limine.conf << EOF
timeout: 5
remember_last_entry: yes
EOF

printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf limine
