#!/usr/bin/env bash
# LFS-AI - Build and install Limine
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=limine
VERSION=10.8.5

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/v$VERSION-binary.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/v$VERSION-binary.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "limine"
tar -xf "v$VERSION-binary.tar.gz"
cd "/sources/limine"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make

rm -rf limeline.exe

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine"
run_log cp -v BOOT* "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/"
run_log cp -v limine-* "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"

run_log mkdir -pv /boot/EFI/LFS
run_log cp -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/limine/BOOTX64.EFI" /boot/EFI/LFS/LIMINEX64.EFI

cat > /boot/limine.conf << EOF
timeout: 5
remember_last_entry: yes
EOF

printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf limine
