#!/usr/bin/env bash
# LFS-AI - Build and install Kbd
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=kbd
VERSION=2.9.0

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
[ -f "/sources/$PACKAGE-$VERSION-backspace-1.patch" ] || die "Missing patch: /sources/$PACKAGE-$VERSION-backspace-1.patch"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i "../$PACKAGE-$VERSION-backspace-1.patch"
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

run_log ./configure --prefix=/usr --disable-vlock
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
run_log cp -R -v docs/doc -T "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
