#!/usr/bin/env bash
# LFS-AI - Build and install E2fsprogs
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=e2fsprogs
VERSION=1.47.4

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_FILE="/logs/lfs/phase5/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

mkdir build
cd    build

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ../configure --prefix=/usr       \
                     --sysconfdir=/etc   \
                     --enable-elf-shlibs \
                     --disable-libblkid  \
                     --disable-libuuid   \
                     --disable-uuidd     \
                     --disable-fsck
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log gunzip -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/libext2fs.info.gz"
run_log install-info --dir-file="/usr/pkg/$PACKAGE/$VERSION/usr/share/info/dir" "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/libext2fs.info"

run_log makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
run_log install -v -m644 doc/com_err.info "/usr/pkg/$PACKAGE/$VERSION/usr/share/info"
run_log install-info --dir-file="/usr/pkg/$PACKAGE/$VERSION/usr/share/info/dir" "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/com_err.info"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
