#!/usr/bin/env bash
# LFS-AI - Build and install E2fsprogs
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=e2fsprogs
VERSION=1.47.4

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase5/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

mkdir build
cd    build

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ../configure --prefix=/usr       \
                     --sysconfdir=/etc   \
                     --enable-elf-shlibs \
                     --disable-libblkid  \
                     --disable-libuuid   \
                     --disable-uuidd     \
                     --disable-fsck
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log gunzip -v "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/libext2fs.info.gz"
run_log install-info --dir-file="/usr/pkg/$PACKAGE/$VERSION/usr/share/info/dir" "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/libext2fs.info"

run_log makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
run_log install -v -m644 doc/com_err.info "/usr/pkg/$PACKAGE/$VERSION/usr/share/info"
run_log install-info --dir-file="/usr/pkg/$PACKAGE/$VERSION/usr/share/info/dir" "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/com_err.info"
printf "${GREEN}Package successful!${RESET}\n"

cat > "/usr/pkg/$PACKAGE/$VERSION/usr/share/info/.graft-exclude" << "EOF"
dir
EOF

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
