#!/usr/bin/env bash
# LFS-AI - Build and install Inih
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=inih
VERSION=62

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase5/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-r$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-r$VERSION.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-r$VERSION"
tar -xf "$PACKAGE-r$VERSION.tar.gz"
cd "/sources/$PACKAGE-r$VERSION"

mkdir -p build
cd       build

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log meson setup --prefix=/usr --buildtype=release ..
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log ninja
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
DESTDIR="/usr/pkg/$PACKAGE/$VERSION" run_log ninja install
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-r$VERSION"
