#!/usr/bin/env bash
# LFS-AI - Build and install Btrfs progs
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=btrfs-progs
VERSION=6.19.1

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase5"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-v$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-v$VERSION.tar.xz"

cd /sources

rm -rf "$PACKAGE-v$VERSION"
tar -xf "$PACKAGE-v$VERSION.tar.xz"
cd "/sources/$PACKAGE-v$VERSION"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr           \
                    --disable-static        \
                    --disable-documentation
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install

run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man5"
run_log mkdir -pv "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man8"

for i in 5 8; do
   run_log install -v Documentation/*."$i" "/usr/pkg/$PACKAGE/$VERSION/usr/share/man/man$i"
done
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-v$VERSION"
