#!/usr/bin/env bash
# LFS-AI - Build and install Nss
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=nss
VERSION=3.121

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/lfs/phase5/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}


[ -f "/sources/nss-standalone-1.patch" ] || {
    printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
        "/sources/nss-standalone-1.patch" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np1 -i ../nss-standalone-1.patch
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
cd nss

run_log make BUILD_OPT=1                      \
        NSPR_INCLUDE_DIR=/usr/include/nspr    \
        USE_SYSTEM_ZLIB=1                     \
        ZLIB_LIBS=-lz                         \
        NSS_ENABLE_WERROR=0                   \
        NSS_USE_SYSTEM_SQLITE=1               \
        "$([ $(uname -m) = x86_64 ] && echo USE_64=1)"
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Packaging %s...${RESET}\n" "$PACKAGE"
cd ../dist

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log install -v -m755 Linux*/lib/*.so              "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log install -v -m644 Linux*/lib/{*.chk,libcrmf.a} "/usr/pkg/$PACKAGE/$VERSION/usr/lib"

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/include/nss"
run_log cp -v -RL {public,private}/nss/*              "/usr/pkg/$PACKAGE/$VERSION/usr/include/nss"

run_log install -v -m755 -d                                        "/usr/pkg/$PACKAGE/$VERSION/usr/bin"
run_log install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} "/usr/pkg/$PACKAGE/$VERSION/usr/bin"

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
run_log install -v -m644 Linux*/lib/pkgconfig/nss.pc  "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
printf "${GREEN}Package successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
