#!/usr/bin/env bash
# LFS-AI - Build and install Nss
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=nss
VERSION=3.122

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/lfs/phase5"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
[ -f "/sources/nss-standalone-1.patch" ] || die "Missing source archive: /sources/nss-standalone-1.patch"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log patch -Np1 -i ../nss-standalone-1.patch
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
cd nss

run_log make BUILD_OPT=1                      \
        NSPR_INCLUDE_DIR=/usr/include/nspr    \
        USE_SYSTEM_ZLIB=1                     \
        ZLIB_LIBS=-lz                         \
        NSS_ENABLE_WERROR=0                   \
        NSS_USE_SYSTEM_SQLITE=1               \
        "$([ $(uname -m) = x86_64 ] && echo USE_64=1)"
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
cd ../dist

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log install -v -m755 Linux*/lib/*.so              "/usr/pkg/$PACKAGE/$VERSION/usr/lib"
run_log install -v -m644 Linux*/lib/{*.chk,libcrmf.a} "/usr/pkg/$PACKAGE/$VERSION/usr/lib"

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/include/nss"
run_log cp -v -RL {public,private}/nss/*              "/usr/pkg/$PACKAGE/$VERSION/usr/include/nss"

run_log install -v -m755 -d                                        "/usr/pkg/$PACKAGE/$VERSION/usr/bin"
run_log install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} "/usr/pkg/$PACKAGE/$VERSION/usr/bin"

run_log install -v -m755 -d                           "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
run_log install -v -m644 Linux*/lib/pkgconfig/nss.pc  "/usr/pkg/$PACKAGE/$VERSION/usr/lib/pkgconfig"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
