#!/usr/bin/env bash
# LFS-AI - Build and install Binutils-pass1 for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=binutils
VERSION=2.46.0

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION-phase1.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: $LFS/sources/$PACKAGE-$VERSION.tar.xz"

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$PACKAGE-$VERSION"

mkdir -p build
cd       build

printf '\n%sConfiguring %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ../configure --prefix="$LFS/tools"  \
                     --with-sysroot="$LFS"  \
                     --target="$LFS_TGT"    \
                     --disable-nls          \
                     --enable-plugins       \
                     --enable-lto           \
                     --disable-werror       \
                     --enable-new-dtags     \
                     --enable-default-hash-style=gnu
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make install
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
