#!/usr/bin/env bash
# LFS-AI - Build and install GCC-pass1 for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=gcc
VERSION=15.2.0

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION-phase1.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: $LFS/sources/$PACKAGE-$VERSION.tar.xz"
[ -f "$LFS/sources/mpfr-4.2.2.tar.xz" ] || die "Missing source archive: $LFS/sources/mpfr-4.2.2.tar.xz"
[ -f "$LFS/sources/gmp-6.3.0.tar.xz" ] || die "Missing source archive: $LFS/sources/gmp-6.3.0.tar.xz"
[ -f "$LFS/sources/mpc-1.4.0.tar.xz" ] || die "Missing source archive: $LFS/sources/mpc-1.4.0.tar.xz"

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$PACKAGE-$VERSION"

tar -xf ../mpfr-4.2.2.tar.xz
mv mpfr-4.2.2 mpfr
tar -xf ../gmp-6.3.0.tar.xz
mv gmp-6.3.0 gmp
tar -xf ../mpc-1.4.0.tar.xz
mv mpc-1.4.0 mpc

case "$(uname -m)" in
    x86_64)
        sed -e '/m64=/s/lib64/lib/' \
            -i.orig gcc/config/i386/t-linux64
        ;;
esac

mkdir -p build
cd       build

printf '%sConfiguring %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ../configure              \
        --target="$LFS_TGT"       \
        --prefix="$LFS/tools"     \
        --with-glibc-version=2.43 \
        --with-sysroot="$LFS"     \
        --with-newlib             \
        --without-headers         \
        --enable-default-pie      \
        --enable-default-ssp      \
        --disable-nls             \
        --disable-shared          \
        --disable-multilib        \
        --disable-threads         \
        --disable-libatomic       \
        --disable-libgomp         \
        --disable-libquadmath     \
        --disable-libssp          \
        --disable-libvtv          \
        --disable-libstdcxx       \
        --enable-plugins          \
        --enable-lto              \
        --enable-languages=c,c++,lto
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s phase 1...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make install

cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
  "$(dirname "$("$LFS_TGT-gcc" -print-libgcc-file-name)")/include/limits.h"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
