#!/usr/bin/env bash
# LFS-AI - Build and install Glibc for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=glibc
VERSION=2.43

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: $LFS/sources/$PACKAGE-$VERSION.tar.xz"
[ -f "$LFS/sources/glibc-fhs-1.patch" ] || die "Missing patch: $LFS/sources/glibc-fhs-1.patch"

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
case "$(uname -m)" in
    i?86)
        run_log ln -svf ld-linux.so.2 "$LFS/lib/ld-lsb.so.3"
        ;;
    x86_64)
        run_log mkdir -pv "$LFS/lib64"
        run_log ln -svf ../lib/ld-linux-x86-64.so.2 "$LFS/lib64/ld-linux-x86-64.so.2"
        run_log ln -svf ../lib/ld-linux-x86-64.so.2 "$LFS/lib64/ld-lsb-x86-64.so.3"
        ;;
esac

run_log patch -Np1 -i ../glibc-fhs-1.patch

mkdir -p build
cd       build

printf 'rootsbindir=/usr/sbin\n' > configparms
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ../configure                         \
        --prefix=/usr                        \
        --host="$LFS_TGT"                    \
        --build="$(../scripts/config.guess)" \
        --disable-nscd                       \
        libc_cv_slibdir=/usr/lib             \
        --enable-kernel=6.6
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="$LFS" install

sed '/RTLDLIST=/s@/usr@@g' -i "$LFS/usr/bin/ldd"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
