#!/usr/bin/env bash
# LFS-AI - Build and install Libstdc++ for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=libstdc++
VERSION=15.2.0
SRC_PACKAGE=gcc

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_DIR="$LFS/var/log/lfs-ai/toolchain"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$SRC_PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: $LFS/sources/$SRC_PACKAGE-$VERSION.tar.xz"

cd "$LFS/sources"

rm -rf "$SRC_PACKAGE-$VERSION"
tar -xf "$SRC_PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$SRC_PACKAGE-$VERSION"

mkdir -p build
cd       build

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ../libstdc++-v3/configure    \
        --host="$LFS_TGT"            \
        --build="$(../config.guess)" \
        --prefix=/usr                \
        --disable-multilib           \
        --disable-nls                \
        --disable-libstdcxx-pch      \
        --with-gxx-include-dir="/tools/$LFS_TGT/include/c++/$VERSION"
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="$LFS" install

run_log rm -vf "$LFS"/usr/lib/lib{stdc++{,exp,fs},supc++}.la
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$SRC_PACKAGE-$VERSION"
