#!/usr/bin/env bash
# LFS-AI - Build and install Libstdc++ for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=libstdc++
VERSION=15.2.0
SRC_PACKAGE=gcc

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd -- "$script_dir/.." && pwd)"
CONFIG_FILE="$base_dir/settings.conf"

source "$CONFIG_FILE"

# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -n "$LFS_TGT" ] || {
    printf "${RED}[ERROR] LFS_TGT is not set.${RESET}\n" >&2
    exit 1
}

[ -f "$LFS/sources/$SRC_PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "$LFS/sources/$SRC_PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd "$LFS/sources"

rm -rf "$SRC_PACKAGE-$VERSION"
tar -xf "$SRC_PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$SRC_PACKAGE-$VERSION"

mkdir -p build
cd       build

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ../libstdc++-v3/configure    \
        --host="$LFS_TGT"            \
        --build="$(../config.guess)" \
        --prefix=/usr                \
        --disable-multilib           \
        --disable-nls                \
        --disable-libstdcxx-pch      \
        --with-gxx-include-dir="/tools/$LFS_TGT/include/c++/$VERSION"
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="$LFS" install

rm -f "$LFS"/usr/lib/lib{stdc++{,exp,fs},supc++}.la
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd "$LFS/sources"
rm -rf "$SRC_PACKAGE-$VERSION"
