#!/usr/bin/env bash
# LFS-AI - Build and install Ncurses for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=ncurses
VERSION=6.6

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd -- "$script_dir/.." && pwd)"
CONFIG_FILE="$base_dir/settings.conf"

source "$CONFIG_FILE"

# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -n "$LFS_TGT" ] || {
    printf "${RED}[ERROR] LFS_TGT is not set.${RESET}\n" >&2
    exit 1
}

[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "$LFS/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "$LFS/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Building tic program...${RESET}\n"
mkdir -p build
pushd    build > /dev/null
  run_log ../configure --prefix="$LFS/tools" AWK=gawk
  run_log make -C include
  run_log make -C progs tic
  run_log install progs/tic "$LFS/tools/bin"
popd > /dev/null
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr                \
                    --host="$LFS_TGT"            \
                    --build="$(./config.guess)"  \
                    --mandir=/usr/share/man      \
                    --with-manpage-format=normal \
                    --with-shared                \
                    --without-normal             \
                    --with-cxx-shared            \
                    --without-debug              \
                    --without-ada                \
                    --disable-stripping          \
                    AWK=gawk
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="$LFS" install

ln -sf libncursesw.so "$LFS/usr/lib/libncurses.so"
sed -e 's/^#if.*XOPEN.*$/#if 1/' \
    -i "$LFS/usr/include/curses.h"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
