#!/usr/bin/env bash
# LFS-AI - Build and install Ncurses for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=ncurses
VERSION=6.6

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: $LFS/sources/$PACKAGE-$VERSION.tar.gz"

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "$LFS/sources/$PACKAGE-$VERSION"

printf '%sBuilding %s tic program...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
mkdir -p build
pushd    build > /dev/null
  run_log ../configure --prefix="$LFS/tools" AWK=gawk
  run_log make -C include
  run_log make -C progs tic
  run_log install progs/tic "$LFS/tools/bin"
popd > /dev/null
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr                \
                    --host="$LFS_TGT"            \
                    --build="$(./config.guess)"  \
                    --mandir=/usr/share/man      \
                    --with-manpage-format=normal \
                    --with-shared                \
                    --without-normal             \
                    --with-cxx-shared            \
                    --without-debug              \
                    --without-ada                \
                    --disable-stripping          \
                    AWK=gawk
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="$LFS" install

run_log ln -svf libncursesw.so "$LFS/usr/lib/libncurses.so"
sed -e 's/^#if.*XOPEN.*$/#if 1/' \
    -i "$LFS/usr/include/curses.h"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
