#!/usr/bin/env bash
# LFS-AI - Build and install Bash for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=bash
VERSION=5.3
PATCH=bash53

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}

[ -n "${LFS:-}" ] || die 'LFS is not set.'
[ -n "${LFS_TGT:-}" ] || die 'LFS_TGT is not set.'


# Log command
LOG_DIR="$LFS/var/log/lfs-ai/toolchain"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: $LFS/sources/$PACKAGE-$VERSION.tar.gz"


for p in {001..009}; do
    [ -f "$LFS/sources/$PATCH-$p" ] || die "Missing patch: $LFS/sources/$PATCH-$p"
done

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "$LFS/sources/$PACKAGE-$VERSION"

printf '%sPatching %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
for p in {001..009}; do
    run_log patch -Np0 -i "../$PATCH-$p"
done
printf '%sPatch successful!%s\n' "$GREEN" "$RESET"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ./configure --prefix=/usr                        \
                    --build="$(sh support/config.guess)" \
                    --host="$LFS_TGT"                    \
                    --without-bash-malloc
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make DESTDIR="$LFS" install

run_log ln -svf bash "$LFS/bin/sh"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
