#!/usr/bin/env bash
# LFS-AI - Build and install Bash for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=bash
VERSION=5.3
PATCH=bash53

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd -- "$script_dir/.." && pwd)"
CONFIG_FILE="$base_dir/settings.conf"

source "$CONFIG_FILE"

# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -n "$LFS_TGT" ] || {
    printf "${RED}[ERROR] LFS_TGT is not set.${RESET}\n" >&2
    exit 1
}

[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "$LFS/sources/$PACKAGE-$VERSION.tar.gz" >&2
    exit 1
}

for p in {001..009}; do
    [ -f "$LFS/sources/$PATCH-$p" ] || {
        printf "${RED}[ERROR] Missing patch: %s${RESET}\n" \
            "$LFS/sources/$PATCH-$p" >&2
        exit 1
    }
done

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "$LFS/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Patching %s...${RESET}\n" "$PACKAGE"
run_log patch -Np0 -i ../"$PATCH-001"
run_log patch -Np0 -i ../"$PATCH-002"
run_log patch -Np0 -i ../"$PATCH-003"
run_log patch -Np0 -i ../"$PATCH-004"
run_log patch -Np0 -i ../"$PATCH-005"
run_log patch -Np0 -i ../"$PATCH-006"
run_log patch -Np0 -i ../"$PATCH-007"
run_log patch -Np0 -i ../"$PATCH-008"
run_log patch -Np0 -i ../"$PATCH-009"
printf "${GREEN}Patch successful!${RESET}\n"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr                        \
                    --build="$(sh support/config.guess)" \
                    --host="$LFS_TGT"                    \
                    --without-bash-malloc
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="$LFS" install

ln -sf bash "$LFS/bin/sh"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
