#!/usr/bin/env bash
# LFS-AI - Build and install Binutils-pass2 for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=binutils
VERSION=2.46.0

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd -- "$script_dir/.." && pwd)"
CONFIG_FILE="$base_dir/settings.conf"

source "$CONFIG_FILE"

# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION-phase2.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -n "$LFS_TGT" ] || {
    printf "${RED}[ERROR] LFS_TGT is not set.${RESET}\n" >&2
    exit 1
}

[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "$LFS/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$PACKAGE-$VERSION"

sed '6031s/$add_dir//' -i ltmain.sh

mkdir -p build
cd       build

printf "${MAGENTA}Configuring %s phase 2...${RESET}\n" "$PACKAGE"
run_log ../configure                 \
        --prefix=/usr                \
        --build="$(../config.guess)" \
        --host="$LFS_TGT"            \
        --disable-nls                \
        --enable-shared              \
        --enable-plugins             \
        --enable-lto                 \
        --disable-werror             \
        --enable-64-bit-bfd          \
        --enable-new-dtags           \
        --enable-default-hash-style=gnu
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s phase 2...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s phase 2...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="$LFS" install

rm -f "$LFS"/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
