#!/usr/bin/env bash
# LFS-AI - Build and install GCC-pass2 for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=gcc
VERSION=15.2.0

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd -- "$script_dir/.." && pwd)"
CONFIG_FILE="$base_dir/settings.conf"

source "$CONFIG_FILE"

# Log command
LOG_FILE="$LFS/logs/toolchain/$PACKAGE-$VERSION-phase2.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -n "$LFS_TGT" ] || {
    printf "${RED}[ERROR] LFS_TGT is not set.${RESET}\n" >&2
    exit 1
}

[ -f "$LFS/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "$LFS/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

[ -f "$LFS/sources/mpfr-4.2.2.tar.xz" ] || {
    printf "${RED}[ERROR] Missing sub-project archive: %s${RESET}\n" \
        "$LFS/sources/mpfr-4.2.2.tar.xz" >&2
    exit 1
}

[ -f "$LFS/sources/gmp-6.3.0.tar.xz" ] || {
    printf "${RED}[ERROR] Missing sub-project archive: %s${RESET}\n" \
        "$LFS/sources/gmp-6.3.0.tar.xz" >&2
    exit 1
}

[ -f "$LFS/sources/mpc-1.4.0.tar.xz" ] || {
    printf "${RED}[ERROR] Missing sub-project archive: %s${RESET}\n" \
        "$LFS/sources/mpc-1.4.0.tar.xz" >&2
    exit 1
}

cd "$LFS/sources"

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "$LFS/sources/$PACKAGE-$VERSION"

tar -xf ../mpfr-4.2.2.tar.xz
mv mpfr-4.2.2 mpfr
tar -xf ../gmp-6.3.0.tar.xz
mv gmp-6.3.0 gmp
tar -xf ../mpc-1.4.0.tar.xz
mv mpc-1.4.0 mpc

case "$(uname -m)" in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

sed '/thread_header =/s/@.*@/gthr-posix.h/' \
    -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir -p build
cd       build

printf "${MAGENTA}Configuring %s phase 2...${RESET}\n" "$PACKAGE"
run_log env LDFLAGS_FOR_TARGET="-L$PWD/$LFS_TGT/libgcc" \
        ../configure                 \
        --build="$(../config.guess)" \
        --host="$LFS_TGT"            \
        --target="$LFS_TGT"          \
        --prefix=/usr                \
        --with-build-sysroot="$LFS"  \
        --enable-default-pie         \
        --enable-default-ssp         \
        --disable-nls                \
        --disable-multilib           \
        --disable-libatomic          \
        --disable-libgomp            \
        --disable-libquadmath        \
        --disable-libsanitizer       \
        --disable-libssp             \
        --disable-libvtv             \
        --enable-plugins             \
        --enable-lto                 \
        --enable-languages=c,c++,lto
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s phase 2...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s phase 2...${RESET}\n" "$PACKAGE"
run_log make DESTDIR="$LFS" install

ln -sf gcc "$LFS/usr/bin/cc"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd "$LFS/sources"
rm -rf "$PACKAGE-$VERSION"
