#!/usr/bin/env bash
# LFS-AI - Build and install libxml2
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=libxml2
VERSION=2.15.2

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/optional"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
sed -i "/'git'/,+3d" meson.build

mkdir -p build
cd       build

run_log meson setup ..            \
              --prefix=/usr       \
              --buildtype=release \
              -D history=enabled  \
              -D icu=enabled
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log ninja
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log env DESTDIR="/usr/pkg/$PACKAGE/$VERSION" ninja install

sed "s/--static/--shared/" -i "/usr/pkg/$PACKAGE/$VERSION/usr/bin/xml2-config"
printf '%sPackage successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log graft -pDV "$PACKAGE/$VERSION"
run_log graft -iV "$PACKAGE/$VERSION"
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
