#!/usr/bin/env bash
# LFS-AI - Build and install Perl for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -euo pipefail

PACKAGE=perl
VERSION=5.42.2
MAJOR_VERSION=5.42

RED=$'\033[31m'
GREEN=$'\033[32m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
RESET=$'\033[0m'


# Error handling
die() {
    printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
    exit 1
}


# Log command
LOG_DIR="/var/log/lfs-ai/chroot"
LOG_FILE="$LOG_DIR/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf '%sERROR:%s %s failed. See %s\n' "$RED" "$RESET" "$*" "$LOG_FILE" >&2
        return 1
    fi
}


[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log sh Configure -des                                                     \
                     -D prefix=/usr                                           \
                     -D vendorprefix=/usr                                     \
                     -D useshrplib                                            \
                     -D privlib=/usr/lib/perl5/"$MAJOR_VERSION"/core_perl     \
                     -D archlib=/usr/lib/perl5/"$MAJOR_VERSION"/core_perl     \
                     -D sitelib=/usr/lib/perl5/"$MAJOR_VERSION"/site_perl     \
                     -D sitearch=/usr/lib/perl5/"$MAJOR_VERSION"/site_perl    \
                     -D vendorlib=/usr/lib/perl5/"$MAJOR_VERSION"/vendor_perl \
                     -D vendorarch=/usr/lib/perl5/"$MAJOR_VERSION"/vendor_perl
printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"

printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make
printf '%sBuild successful!%s\n' "$GREEN" "$RESET"

printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
run_log make install
printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"

cd /sources
rm -rf "$PACKAGE-$VERSION"
