#!/usr/bin/env bash
# LFS-AI - Build and install Python for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=Python
VERSION=3.14.3

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/chroot/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$*" "$LOG_FILE" >&2
        return 1
    fi
}

[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$PACKAGE-$VERSION.tar.xz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$PACKAGE-$VERSION.tar.xz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
run_log ./configure --prefix=/usr       \
                    --enable-shared     \
                    --without-ensurepip \
                    --without-static-libpython
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log make install
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION"
