#!/usr/bin/env bash
# LFS-AI - Build and install Graft for the toolchain
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

PACKAGE=graft
VERSION=2.16

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'

# Log command
LOG_FILE="/logs/chroot/$PACKAGE-$VERSION.log"

run_log() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}[ERROR] %s failed. See %s${RESET}\n" "$1" "$LOG_FILE" >&2
        return 1
    fi
}

run_log_error() {
    if "$@" >> "$LOG_FILE" 2>&1; then
        return 0
    else
        printf "${RED}There was an error, however it is normal here.${RESET}\n" >&2
        return 1
    fi
}

[ -f "/sources/$VERSION.tar.gz" ] || {
    printf "${RED}[ERROR] Missing source archive: %s${RESET}\n" \
        "/sources/$VERSION.tar.gz" >&2
    exit 1
}

cd /sources

rm -rf "$PACKAGE-$VERSION"
tar -xf "$VERSION.tar.gz"
cd "/sources/$PACKAGE-$VERSION"

printf "${MAGENTA}Configuring %s...${RESET}\n" "$PACKAGE"
set +e
run_log_error make -f Makefile.dist
set -e

sed -i \
  -e 's|^PACKAGEDIR[[:space:]]*=.*|PACKAGEDIR = /usr/pkg|' \
  -e 's|^TARGETDIR[[:space:]]*=.*|TARGETDIR = /|' \
  -e 's|^BIN[[:space:]]*=.*|BIN = $(TOP)/usr/bin|' \
  -e 's|^MAN[[:space:]]*=.*|MAN = $(TOP)/usr/share/man|' \
  -e 's|^DOC[[:space:]]*=.*|DOC = $(TOP)/usr/share/doc/graft-2.16|' \
  Makefile
printf "${GREEN}Configuration successful!${RESET}\n"

printf "${MAGENTA}Building %s...${RESET}\n" "$PACKAGE"
run_log make
printf "${GREEN}Build successful!${RESET}\n"

printf "${MAGENTA}Installing %s...${RESET}\n" "$PACKAGE"
run_log make install

rm -f /usr/pkg/"$PACKAGE-$VERSION"/usr/share/doc/"$PACKAGE-$VERSION"/.nograft

run_log /usr/pkg/"$PACKAGE-$VERSION"/usr/bin/graft -iV "$PACKAGE-$VERSION"
printf "${GREEN}Install successful!${RESET}\n\n\n"

cd /sources
rm -rf "$PACKAGE-$VERSION" "$VERSION.tar.gz"
