#!/usr/bin/env bash
# LFS-AI - Toolchain-Chroot Script
# Purpose: Install remaining directories and toolchain inside chroot
# Safe rerun: Yes
# Copyright (c) 2026 Michael Femiak (Vercety1534)
# SPDX-License-Identifier: MIT

set -e

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
MAGENTA='\033[35m'
RESET='\033[0m'




# Create directories
printf "${GREEN}Entered chroot!${RESET}\n"
printf "\n${MAGENTA}Creating directories...${RESET}\n"
mkdir -p /{home,mnt,opt,srv}

mkdir -p /etc/{opt,sysconfig}
mkdir -p /lib/firmware
mkdir -p /media/{floppy,cdrom}
mkdir -p /usr/{,local/}{include,src}
mkdir -p /usr/lib/locale
mkdir -p /usr/local/{bin,lib,sbin}
mkdir -p /usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -p /usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -p /usr/{,local/}share/man/man{1..8}
mkdir -p /var/{cache,local,log,mail,opt,spool}
mkdir -p /var/lib/{color,misc,locate}

ln -sf /run /var/run
ln -sf /run/lock /var/lock

install -d -m 0750 /root
install -d -m 1777 /tmp /var/tmp

rm -rf /logs/chroot
mkdir -p /logs/chroot
printf "${GREEN}Creation successful!${RESET}\n"




# Create essential files and symlinks
printf "\n${MAGENTA}Creating essential files...${RESET}\n"
ln -sf /proc/self/mounts /etc/mtab

cat > /etc/hosts << EOF
127.0.0.1  localhost "$(hostname)"
::1        localhost
EOF

cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/usr/bin/false
systemd-journal-remote:x:74:74:systemd Journal Remote:/:/usr/bin/false
systemd-journal-upload:x:75:75:systemd Journal Upload:/:/usr/bin/false
systemd-network:x:76:76:systemd Network Management:/:/usr/bin/false
systemd-resolve:x:77:77:systemd Resolver:/:/usr/bin/false
systemd-timesync:x:78:78:systemd Time Synchronization:/:/usr/bin/false
systemd-coredump:x:79:79:systemd Core Dumper:/:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
systemd-oom:x:81:81:systemd Out Of Memory Daemon:/:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF

cat > /etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
clock:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
kvm:x:61:
systemd-journal-gateway:x:73:
systemd-journal-remote:x:74:
systemd-journal-upload:x:75:
systemd-network:x:76:
systemd-resolve:x:77:
systemd-timesync:x:78:
systemd-coredump:x:79:
uuidd:x:80:
systemd-oom:x:81:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF

grep -q '^tester:' /etc/passwd || \
    printf "tester:x:101:101::/home/tester:/bin/bash\n" >> /etc/passwd

grep -q '^tester:' /etc/group || \
    printf "tester:x:101:\n" >> /etc/group

install -o tester -d /home/tester

touch /var/log/{btmp,lastlog,faillog,wtmp}
chgrp utmp /var/log/lastlog
chmod --quiet 664  /var/log/lastlog
chmod --quiet 600  /var/log/btmp
printf "${GREEN}File creation successful!${RESET}\n\n"




# Run install scripts
[ -d /lfs-ai/chroot ] || {
    printf "${RED}[ERROR] Missing /lfs-ai/chroot${RESET}\n" >&2
    exit 1
}

cd /lfs-ai

found_script=0
for script in /lfs-ai/chroot/*; do
    if [ -f "$script" ] && [ -x "$script" ]; then
        found_script=1
        bash "$script"
    fi
done

[ "$found_script" -eq 1 ] || {
    printf "${RED}ERROR:${RESET} No executable scripts found in /lfs-ai/chroot\n" >&2
    exit 1
}




# Clean up temporary system
printf "\n${MAGENTA}Cleaning up temporary files...${RESET}\n"
rm -rf /usr/share/{info,man,doc}/*

find /usr/{lib,libexec} -name \*.la -delete

rm -rf /tools
printf "${GREEN}Temporary files cleaned up. Build environment complete!${RESET}\n"
